version: '3.8'

services:
  
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: smart-tracker-frontend-jojo
    ports:
      - "3000:3000"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: